
name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Test Suite
        run: test/bats/bin/bats --verbose-run test/tests/
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build single executable script
        run: |
          cd $GITHUB_WORKSPACE
          ./build.sh main.sh nbac
      - uses: actions/upload-artifact@v3
        with:
          name: nbac
          path: nbac
          if-no-files-found: error
